name: Install modules

on:
  workflow_dispatch:

concurrency:
  group: install-modules

permissions: {}

jobs:
  install-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
          
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Run install
        run: npm install
          
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.TOKEN }}
          delete-branch: true
          branch: node_modules
          commit-message: "node_modules: install"
          title: "node_modules: install"
